# AI 生图识别脚本（基于元数据 / 签名）
# 检测 Stable Diffusion/ComfyUI/NovelAI/DALL·E/Midjourney/Firefly 及 C2PA 内容凭证等 AI 生成特征
import sys
import os
import re

# 统一以 UTF-8 输出，避免在中文 Windows 控制台/管道下 emoji 触发 GBK 编码错误
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")


def gather_metadata(path):
    """收集图片中可读的文本类元数据，返回 {来源: 文本}"""
    from PIL import Image, ExifTags  # 延迟导入：无 Pillow 时仍可使用纯逻辑函数
    texts = {}
    img = Image.open(path)

    for k, v in (img.info or {}).items():
        if isinstance(v, bytes):
            v = v.decode('latin-1', 'ignore')
        if isinstance(v, str) and v.strip():
            texts[f"info:{k}"] = v

    if hasattr(img, 'text'):
        for k, v in img.text.items():
            texts[f"text:{k}"] = str(v)

    try:
        exif = img._getexif() or {}
        for tid, v in exif.items():
            name = ExifTags.TAGS.get(tid, tid)
            if isinstance(v, bytes):
                enc = 'utf-16le' if tid in (40091, 40092, 40093, 40094, 40095) else 'latin-1'
                v = v.decode(enc, 'ignore').rstrip('\x00')
            if str(v).strip():
                texts[f"exif:{name}"] = str(v)
    except Exception:
        pass

    return texts


def extract_xmp(data):
    """从原始字节中提取 XMP 包文本（常含 AI / C2PA 标记）"""
    start = data.find(b'<x:xmpmeta')
    end = data.find(b'</x:xmpmeta>')
    if start != -1 and end != -1 and end > start:
        return data[start:end + 12].decode('utf-8', 'ignore')
    return ""


def detect(texts, data, xmp):
    """返回 [(标签, 是否强信号, 证据)]"""
    findings = []
    # 元数据文本合并（小写用于匹配）
    blob = "\n".join(f"{k}={v}" for k, v in texts.items()) + "\n" + xmp
    low = blob.lower()
    raw_low = data.lower()  # 原始字节，捕获 C2PA/JUMBF 等二进制标记

    def has(*subs):
        return all(s in low for s in subs)

    # —— 强信号：明确的生成工具特征 ——
    if has('steps:', 'sampler:') or has('steps:', 'cfg scale:'):
        findings.append(("Stable Diffusion WebUI (AUTOMATIC1111) 参数块", True,
                         _snippet(texts, ('info:parameters', 'text:parameters'))))
    if '"class_type"' in low or 'comfyui' in low or ('info:workflow' in texts) or ('info:prompt' in texts):
        findings.append(("ComfyUI 工作流 (prompt/workflow)", True,
                         _snippet(texts, ('info:prompt', 'info:workflow'))))
    if 'novelai' in low:
        findings.append(("NovelAI", True, _snippet(texts, ('info:Software', 'exif:Software'))))
    if 'invokeai' in low or 'sd-metadata' in low or 'info:Dream' in texts:
        findings.append(("InvokeAI", True, _snippet(texts, ('info:sd-metadata', 'info:Dream'))))
    if 'midjourney' in low or 'job id' in low:
        findings.append(("Midjourney", True, _snippet(texts, ('exif:ImageDescription', 'exif:Artist'))))
    if 'dall-e' in low or 'dall·e' in low or 'openai' in low:
        findings.append(("OpenAI DALL·E", True, ""))
    if 'firefly' in low:
        findings.append(("Adobe Firefly", True, ""))
    if 'stability.ai' in low or 'stable diffusion' in low:
        findings.append(("Stability AI / Stable Diffusion", True, ""))
    if 'made with google ai' in low or 'gemini' in low or 'imagen' in low:
        findings.append(("Google AI (Imagen/Gemini)", True, ""))

    # C2PA / 内容凭证：digitalSourceType 为训练算法媒体 => 强信号
    if b'trainedalgorithmicmedia' in raw_low or 'trainedalgorithmicmedia' in low \
            or 'compositewithtrainedalgorithmicmedia' in low:
        findings.append(("C2PA 内容凭证: digitalSourceType=trainedAlgorithmicMedia", True, ""))
    elif b'jumb' in raw_low and (b'c2pa' in raw_low or 'contentcredentials' in low or 'contentauth' in low):
        findings.append(("C2PA / 内容凭证 (Content Credentials) 存在", False,
                         "含内容凭证，但未明确标注为 AI 生成，需查看凭证详情"))

    # —— 弱信号：泛化关键字 ——
    for kw, label in [('aigc', 'AIGC 标记'),
                      ('generated by ai', '“generated by AI”'),
                      ('ai generated', '“AI generated”'),
                      ('ai-generated', '“AI-generated”'),
                      ('artificial intelligence', '“artificial intelligence”')]:
        if kw in low:
            findings.append((f"泛化 AI 关键字: {label}", False, ""))

    return findings


def _snippet(texts, keys, limit=200):
    for k in keys:
        if k in texts:
            s = texts[k].replace('\n', ' ').strip()
            return (s[:limit] + '…') if len(s) > limit else s
    return ""


def analyze(path):
    result = f"🤖 AI 生图元数据检测: {os.path.basename(path)}\n"
    result += "=" * 60 + "\n"

    texts = gather_metadata(path)
    with open(path, 'rb') as f:
        data = f.read()
    xmp = extract_xmp(data)

    findings = detect(texts, data, xmp)
    # 去重（按标签）
    seen = {}
    for label, strong, ev in findings:
        if label not in seen:
            seen[label] = (strong, ev)

    strong_hits = [(l, e) for l, (s, e) in seen.items() if s]
    weak_hits = [(l, e) for l, (s, e) in seen.items() if not s]

    if strong_hits:
        result += "🔴 结论: 极可能为 AI 生成\n\n命中特征:\n"
        for label, ev in strong_hits:
            result += f"  ✅ {label}\n"
            if ev:
                result += f"      证据: {ev}\n"
    elif weak_hits:
        result += "🟡 结论: 疑似 AI 生成 / 含 AI 相关元数据，建议人工确认\n\n命中特征:\n"
        for label, ev in weak_hits:
            result += f"  • {label}\n"
            if ev:
                result += f"      说明: {ev}\n"
    else:
        result += "⚪ 结论: 未发现 AI 生成相关的元数据特征\n"
        result += "   注意: 元数据可被截图 / 重新保存 / 工具清除，无此特征不代表一定为真实拍摄。\n"

    # 列出可供人工研判的关键元数据
    interesting = {k: v for k, v in texts.items()
                   if k.split(':', 1)[-1].lower() in
                   ('parameters', 'prompt', 'workflow', 'software', 'comment',
                    'description', 'usercomment', 'artist', 'sd-metadata', 'dream')}
    if interesting:
        result += "\n📋 关键元数据:\n"
        for k, v in interesting.items():
            v = v.replace('\n', ' ').strip()
            v = (v[:300] + '…') if len(v) > 300 else v
            result += f"  [{k}] {v}\n"

    if xmp:
        result += f"\n🧾 检测到 XMP 包 ({len(xmp)} 字节)\n"

    return result


if __name__ == "__main__":
    if len(sys.argv) > 1:
        try:
            print(analyze(sys.argv[1]))
        except FileNotFoundError:
            print(f"❌ 文件不存在: {sys.argv[1]}")
        except Exception as e:
            print(f"❌ 分析出错: {e}")
    else:
        print("❌ 请提供图片路径作为参数")
        print("使用方法: python ai_detect.py <图片路径>")
